Add in support for AWS session tokens
whereisaaron/get-aws-profile-bash pull request #3
Opened 2018-08-07 18:59 UTC by alexlatchford

Great little script! We have a need to grab session tokens (for federated logins) so I've added support let me know what you think

2018-08-08 04:02 UTC, whereisaaron requested changes
Looks good! You just need to update this documentation to mention the new option

echo "  You can specify one --key or --secret to get just that value, with no line break,"

2018-08-08 04:04 UTC, whereisaaron commented on get-aws-profile.sh
>    echo "  You can specify one --key or --secret to get just that value, with no line break,"
Update this comment for the new option and we are good to go

2018-10-14 04:37 UTC, mkj28 commented
@alexlatchford  plz :) update/let's get it in :)

2018-10-14 17:32 UTC, merged

2018-10-14 17:33 UTC, whereisaaron commented
Hi @mkj28 @alexlatchford, I updated the usage comment myself and merged it.

2018-10-14 18:40 UTC, mkj28 commented
awesome, thanks!